### ISSUE TITLE
Release tag points to incorrect commit SHA

### ISSUE THREAD

**Issue by MerricdeLauney** [dpb587/bosh-release-resource#7] opened 2019-09-04 18:07 UTC
Hello,

There is some code [here](https://github.com/dpb587/bosh-release-resource/blob/e6fd047e93ef897e0dc1316cbb4c4dd106297781/out/main.go#L64-L80): 

```go
	versionCommitHash, err := release.FinalizeRelease(releaseName, version, tarballPath)
	if err != nil {
		api.Fatal(errors.Wrap(err, "bad release tarball"))
	}

	commit, err := repository.Commit(commitMessage, request.Params.Rebase)
	if err != nil {
		api.Fatal(errors.Wrap(err, "bad commit"))
	}

	if !request.Params.SkipTag {
		tag := fmt.Sprintf("v%s", version)
		err = repository.Tag(versionCommitHash, tag, tag)
		if err != nil {
			api.Fatal(errors.Wrap(err, "bad tag"))
		}
	}
```

Here, `versionCommitHash` is the commit SHA found inside the release manifest (`releases/<>/foo-21.yml`), which is the commit that the final release was built on.

Right below, we make a commit with all the final release artifacts.

After that, we tag the repository...but we do so using `versionCommitHash` instead of `commit`.

**Comment by dpb587** [comment] 2019-09-04 18:55
Hi – if I understand correctly, what you're describing is expected behavior of this resource – it intentionally tags from the `commit_hash` of the manifest, not the commit which is made. From the [Caveats](https://github.com/dpb587/bosh-release-resource#caveats) section of the readme:

> This tags the commit from which the release tarball was created (`commit_hash`), not the commit which finalizes the release in the `releases` directory. This is primarily to ensure git tags match `commit_hash` and refer to the underlying source where changes between versions occur (as opposed to when it was finalized which may have a different set of files).

This behavior hasn't changed since the resource was first released. Are you seeing a particular problem with this approach, or is it just a surprise / unset expectations? Happy to chat more.

**Comment by dpb587** [comment] 2019-09-10 06:00
Closing - working as expected and discussed further offline.

**Closed as completed by dpb587** 2019-09-10 06:00 UTC
